- name: Install Docker
  become: true
  apt:
    name:
      - docker.io
      - docker-compose
      - python3-docker

- name: Enable and start Docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: true
